# Generated by Django 5.2 on 2025-04-27 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(max_length=35)),
                ('cidade', models.CharField(max_length=35)),
                ('estado', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('genero', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('data_cadastro', models.DateTimeField()),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.endereco')),
            ],
        ),
    ]
